### ISSUE TITLE
Call back and alternative calling procedures resource

### ISSUE THREAD

**Issue by strogonoff** [ituob/itu-ob-data#8]
It looks like call back and alternative calling procedures are handled by a different resource than OB, and merely linked to from OB via URL http://www.itu.int/pub/T-SP-PP.RES.21-2011/.

The link appears to stay the same from OB issue 1163 to 1173, so perhaps it never changes? Does ITU have plans to include detailed callback/alt call procedures in the OB, or will it stay linked to an external resource?

**Comment by ronaldtse** [comment]
@strogonoff it is part of the OB, but expressed through a link. The linked resource is a list, there are no procedures in that resource.

This list means that the countries listed consider "Call Back" procedures as an illegal method of calling, and therefore is an "exception" to procedures. That's why it is in the OB (a temporary service restriction).

No one knows if it will change, so assume it to be there for now.
